version: 2
sources:
  - name: gz_raw_data 
    tables:
      - name: raw_gz_sales
        identifier: sales
        
      - name: raw_gz_ship
        identifier: ship
        
      - name: raw_gz_product
        identifier: product